image: jelaniwoods/appdev2023-base-ruby

tasks:
  - before: |
      source $(rvm 3.1.2 do rvm env --path)
      bin/setup
      .vscode/manage_extensions

ports:
  - port: 3000
    onOpen: open-preview
  - port: 9500-9999
    onOpen: ignore

vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - aliariff.vscode-erb-beautify
